blog:
  component: "@sls-next/serverless-component@3.2.0"
  inputs:
    domain: ["www", "banyudu.com"]
    cloudfront:
      # if you want to use an existing cloudfront distribution, provide it here
      distributionId: BANYUDUBLOG #optional
