service: "blog"
frameworkVersion: "^2.1.0"
variablesResolutionMode: 20210326

custom:
  stage: ${opt:stage, "dev"}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  serverless-offline:
    port: 3886
  domains:
    prod: api.banyudu.com
    staging: staging-api.banyudu.com
    dev: dev-api.banyudu.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}} # Change this to your domain.
    basePath: 'blog' # This will be prefixed to all routes
    stage: ${self:custom.stage}
    createRoute53Record: true
  sentry:
    dsn: ${self:provider.environment.sentryDSN}
  blogTable: '${self:service}-${self:custom.stage}'
  seriesTable: '${self:service}-series-${self:custom.stage}'


# Add the serverless-webpack plugin
plugins:
  - serverless-sentry
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  memorySize: 256
  environment:
    stage: ${opt:stage, self:provider.stage}
    sentryDSN: ${ssm:/${self:service}/sentryDSN}
    githubToken: ${ssm:/${self:service}/githubToken}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    blogTable: ${self:custom.blogTable}
    seriesTable: ${self:custom.seriesTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - { "Fn::GetAtt": ["Table", "Arn" ] }
        - { "Fn::Join": [ "/", [
          { "Fn::GetAtt": ["Table", "Arn" ] }, "index", "urlGSI"
        ]]}
        - { "Fn::Join": [ "/", [
          { "Fn::GetAtt": ["Table", "Arn" ] }, "index", "seriesGSI"
        ]]}
        - { "Fn::GetAtt": ["SeriesTable", "Arn" ] }
        - { "Fn::Join": [ "/", [
          { "Fn::GetAtt": ["SeriesTable", "Arn" ] }, "index", "urlGSI"
        ]]}

functions:
  getCategories:
    handler: handler.getCategories
    events:
      - http:
          method: get
          path: categories
          cors: true
  getTags:
    handler: handler.getTags
    events:
      - http:
          method: get
          path: tags
          cors: true
  getPosts:
    handler: handler.getPosts
    events:
      - http:
          method: get
          path: posts
          cors: true
  getPost:
    handler: handler.getPost
    events:
      - http:
          method: get
          path: post/{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
  getGists:
    handler: handler.getGists
    events:
      - http:
          method: get
          path: gists
          cors: true
  syncGists:
    handler: handler.syncGists
    events:
      - http:
          method: post
          path: sync
          cors: true
      - schedule: rate(1 hour)
  getSiteMap:
    handler: handler.getSiteMap
    events:
      - http:
          method: get
          path: /sitemap.xml.gz
          cors: true

resources:
  Resources:
    Table:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: url
            AttributeType: S
          - AttributeName: series
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.blogTable}
        GlobalSecondaryIndexes:
          - IndexName: urlGSI
            KeySchema:
              - AttributeName: url
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: seriesGSI
            KeySchema:
              - AttributeName: series
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    SeriesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.seriesTable}
        GlobalSecondaryIndexes:
          - IndexName: urlGSI
            KeySchema:
              - AttributeName: url
                KeyType: HASH
            Projection:
              ProjectionType: ALL
