on:
  push:
    tags:
      - 'admin@*'
name: Deploy Admin
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm i -g serverless
    - run: npm ci
      working-directory: ./packages/admin
    - run: |
        echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
        echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
      working-directory: ./packages/admin
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
    - run: sls --debug
      working-directory: ./packages/admin
