name: npm audit

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: install dependencies
        run: npm ci
      - run: npx lerna-audit && npm run lint:fix && git commit --amend --no-edit --author="npm-audit-bot"
      - uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: npm audit
